### ISSUE TITLE
I'm getting segmentation fault when trying to deploy the container

### ISSUE THREAD

**Issue by panosru** [chartbrew/chartbrew#205] opened 2024-03-06 01:31 UTC
I think that I followed the guides properly but I might've missed something... 

Here is the output I get when I run `BASE_URL=http://localhost docker compose up chartbrew`

```
BASE_URL=http://localhost docker compose up chartbrew
[+] Running 7/7
 ✔ Network strapi_default      Created                                                                                                                                                        0.0s
 ✔ Volume "strapi_chartbrew"   Created                                                                                                                                                        0.0s
 ✔ Volume "strapi_pgdata"      Created                                                                                                                                                        0.0s
 ✔ Container strapi-db         Created                                                                                                                                                        0.4s
 ✔ Container strapi-chartbrew  Created                                                                                                                                                        1.0s
Attaching to strapi-chartbrew
strapi-chartbrew  | The UI is rebuilding. Please wait...
strapi-chartbrew  |
strapi-chartbrew  | > client-new@v3.1.1 preview
strapi-chartbrew  | > vite preview
strapi-chartbrew  |
strapi-chartbrew  |
strapi-chartbrew  | > client-new@v3.1.1 build
strapi-chartbrew  | > npm run prepareSettings && vite build
strapi-chartbrew  |
strapi-chartbrew  |
strapi-chartbrew  | > client-new@v3.1.1 prepareSettings
strapi-chartbrew  | > echo n | cp -vipr src/config/settings.template.js src/config/settings.js | true
strapi-chartbrew  |
strapi-chartbrew  | cp: overwrite 'src/config/settings.js'? Segmentation fault
strapi-chartbrew  | Segmentation fault
strapi-chartbrew exited with code 139
```

And this is my docker compose YAML file:

```yaml
version: '3.9'

services:

  chartbrew:
    image: razvanilin/chartbrew
    container_name: 'strapi-chartbrew'
    logging:
      driver: "json-file"
      options:
        max-size: '1m'
        max-file: '1'
    #restart: always
    ports:
      - "4018:4018"
      - "4019:4019"
    expose:
      - 4018
      - 4019
    environment:
      CB_SECRET: ${ADMIN_PASSWORD:-chartbrew}
      CB_API_HOST: 0.0.0.0
      CB_API_PORT: 4019
      CB_DB_DIALECT: postgres
      CB_DB_HOST: db
      CB_DB_PORT: 5432
      CB_DB_NAME: chartbrew
      CB_DB_USERNAME: strapi
      CB_DB_PASSWORD: strapi
      VITE_APP_CLIENT_HOST: "${BASE_URL}:4018"
      VITE_APP_CLIENT_PORT: 4018
      VITE_APP_API_HOST: "${BASE_URL}:4019"
    volumes:
      - chartbrew:/code/client/dist
    depends_on:
      - db
  
  db:
    image: postgres:16.2-alpine
    container_name: 'strapi-db'
    healthcheck:
      test: [ "CMD", "pg_isready", "-h", "localhost",
          "-p", "5432", "-U", "${POSTGRES_USER:-strapi}"]
      interval: 10s
      timeout:  5s
      retries:  3
    logging:
      driver: "json-file"
      options:
        max-size: '1m'
        max-file: '1'
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME:-strapi}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-strapi}
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
      LANG: en_US.utf8
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres.init.sql:/docker-entrypoint-initdb.d/postgres.init.sql

volumes:
  chartbrew: {}
  pgdata: {}
```

The content of `postgres.init.sql` is this:
```sql
CREATE DATABASE "chartbrew"
    WITH
    OWNER = strapi
    ENCODING = 'UTF8'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;
    
CREATE DATABASE "strapi"
    WITH
    OWNER = strapi
    ENCODING = 'UTF8'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;
```

I have also tried with MySQL and I was getting the same result.

Thanks!

**Comment by panosru** [comment] 2024-03-06 09:54
I gave it a second shot with lightly different configuration for the volume but I'm still getting:

```
Attaching to strapi-chartbrew
strapi-chartbrew  | The UI is rebuilding. Please wait...
strapi-chartbrew  |
strapi-chartbrew  | > client-new@v3.1.1 preview
strapi-chartbrew  | > vite preview
strapi-chartbrew  |
strapi-chartbrew  |
strapi-chartbrew  | > client-new@v3.1.1 build
strapi-chartbrew  | > npm run prepareSettings && vite build
strapi-chartbrew  |
strapi-chartbrew  |
strapi-chartbrew  | > client-new@v3.1.1 prepareSettings
strapi-chartbrew  | > echo n | cp -vipr src/config/settings.template.js src/config/settings.js | true
strapi-chartbrew  |
strapi-chartbrew  |   ➜  Local:   http://localhost:4018/
strapi-chartbrew  |   ➜  Network: http://172.18.0.3:4018/
strapi-chartbrew  | vite v5.0.10 building for production...
strapi-chartbrew  | transforming...
strapi-chartbrew  | cp: overwrite 'src/config/settings.js'? Segmentation fault
strapi-chartbrew  | HostNotFoundError [SequelizeHostNotFoundError]: getaddrinfo ENOTFOUND db
strapi-chartbrew  |     at Client._connectionCallback (/code/server/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:134:24)
strapi-chartbrew  |     at Client._handleErrorWhileConnecting (/code/server/node_modules/pg/lib/client.js:327:19)
strapi-chartbrew  |     at Client._handleErrorEvent (/code/server/node_modules/pg/lib/client.js:337:19)
strapi-chartbrew  |     at Connection.emit (node:events:518:28)
strapi-chartbrew  |     at Socket.reportStreamError (/code/server/node_modules/pg/lib/connection.js:58:12)
strapi-chartbrew  |     at Socket.emit (node:events:518:28)
strapi-chartbrew  |     at emitErrorNT (node:internal/streams/destroy:169:8)
strapi-chartbrew  |     at emitErrorCloseNT (node:internal/streams/destroy:128:3)
strapi-chartbrew  |     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
strapi-chartbrew  |   parent: Error: getaddrinfo ENOTFOUND db
strapi-chartbrew  |       at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
strapi-chartbrew  |     errno: -3008,
strapi-chartbrew  |     code: 'ENOTFOUND',
strapi-chartbrew  |     syscall: 'getaddrinfo',
strapi-chartbrew  |     hostname: 'db'
strapi-chartbrew  |   },
strapi-chartbrew  |   original: Error: getaddrinfo ENOTFOUND db
strapi-chartbrew  |       at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
strapi-chartbrew  |     errno: -3008,
strapi-chartbrew  |     code: 'ENOTFOUND',
strapi-chartbrew  |     syscall: 'getaddrinfo',
strapi-chartbrew  |     hostname: 'db'
strapi-chartbrew  |   }
strapi-chartbrew  | }
strapi-chartbrew  | Migrations failed, could not run the server app.
```

**Comment by razvanilin** [comment] 2024-03-06 11:54
It looks like the issue is that `CB_DB_HOST` is being set with the string `db`. Replacing the value with the actual host of the database should fix the issue

**Comment by panosru** [comment] 2024-03-06 12:04
I have tried both with `CB_DB_HOST: db` and `CB_DB_HOST: 'strapi-db'`, I am getting the same `Segmentation fault` either way

**Comment by panosru** [comment] 2024-03-06 12:09
I also just tried the following:
```
docker exec -ti strapi-db bash
46f99381c4b2:/# /sbin/ip route|awk '/default/ { print $3 }'
172.19.0.1
```

and I replaced: `CB_DB_HOST: 172.19.0.1` I also tried `CB_DB_HOST: host.docker.internal`, still, same issue.

**Comment by panosru** [comment] 2024-03-17 13:14
It seems that this is happening in Docker for macOS. I tested it in Linux and it works fine. I tried to switch from `VirtioFS` to either `gRPC FUSE` or `osxfs (Legacy)` to disable the `Use Virtualization framework`, but neither worked because Docker was constantly crashing.

**Comment by razvanilin** [comment] 2024-03-18 04:35
Thanks for the update @panosru 🙏 I just checked my Docker settings and I use `VirtioFS` and I'm on a Mac. Do you have any pending updates for Docker? Also, can you let me know what Mac you have and which MacOS version you're currently on?

**Comment by panosru** [comment] 2024-03-18 18:26
I'm on macOS v14.4 (Intel) and my nvme drive has APFS format. I'm using docker desktop v4.28.0 with docker engine v25.0.3 and compose v2.24.6-desktop.1. It also seems that segmentation fault issues with node.js related containers [are not as unusual](https://github.com/docker/for-mac/issues/6824) as I thought.

**Comment by razvanilin** [comment] 2024-03-19 05:05
Thanks for the updates @panosru

Looking at the issue, it seems that it's related to Docker's client on Intel Macs. I'll close this issue as it's not related to Chartbrew, but if you notice something that can be changed from Chartbrew's side to make it work in your environment, feel free to let me know here ✌️

**Closed by razvanilin** 2024-03-19 05:05 UTC

**Comment by panosru** [comment] 2024-03-19 09:21
@razvanilin yes, you are correct! Just for some info in case someone else stumbles upon this. I'm on a Hackintosh (both intel virtualization and vd-t are enabled in BIOS) all my VMs are working fine (Parallels, VBox, VMWare, Docker, etc.), it seems though that since Docker Desktop is forcing you to use Apple Virtualisation Framework, it is where the complications start. Note: That is not only related to Hackintosh but also to native Intel apple machines. The solution is simple (at least it worked for me). 

1. Completely remove Docker Desktop:

First run `/Applications/Docker.app/Contents/MacOS/uninstall` then run these commands (or create an sh file with chmod +x to run them all)

```bash
sudo rm -Rf /Applications/Docker.app
sudo rm -f /usr/local/bin/docker
sudo rm -f /usr/local/bin/docker-machine
sudo rm -f /usr/local/bin/docker-compose
sudo rm -f /usr/local/bin/docker-credential-desktop
sudo rm -f /usr/local/bin/docker-credential-ecr-login
sudo rm -f /usr/local/bin/docker-credential-osxkeychain
sudo rm -Rf ~/.docker
sudo rm -Rf ~/Library/Containers/com.docker.docker
sudo rm -Rf ~/Library/Application\ Support/Docker\ Desktop
sudo rm -Rf ~/Library/Group\ Containers/group.com.docker
sudo rm -f ~/Library/HTTPStorages/com.docker.docker.binarycookies
sudo rm -f /Library/PrivilegedHelperTools/com.docker.vmnetd
sudo rm -f /Library/LaunchDaemons/com.docker.vmnetd.plist
sudo rm -Rf ~/Library/Logs/Docker\ Desktop
sudo rm -Rf /usr/local/lib/docker
sudo rm -f ~/Library/Preferences/com.docker.docker.plist
sudo rm -Rf ~/Library/Saved\ Application\ State/com.electron.docker-frontend.savedState
sudo rm -f ~/Library/Preferences/com.electron.docker-frontend.plist
```

2. Install Rancher Desktop for macOS

Now this container (and most likely all other containers affected by similar issues) works:
```
The UI is rebuilding. Please wait...
> client-new@v3.2.0 preview
> vite preview
> client-new@v3.2.0 build
> npm run prepareSettings && vite build
  ➜  Local:   http://localhost:4018/
  ➜  Network: http://172.18.0.3:4018/
> client-new@v3.2.0 prepareSettings
> echo n | cp -vipr src/config/settings.template.js src/config/settings.js | true
vite v5.1.6 building for production...
transforming...
cp: overwrite 'src/config/settings.js'? HostNotFoundError [SequelizeHostNotFoundError]: getaddrinfo ENOTFOUND db
    at Client._connectionCallback (/code/server/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:136:24)
    at Client._handleErrorWhileConnecting (/code/server/node_modules/pg/lib/client.js:327:19)
    at Client._handleErrorEvent (/code/server/node_modules/pg/lib/client.js:337:19)
    at Connection.emit (node:events:518:28)
    at Socket.reportStreamError (/code/server/node_modules/pg/lib/connection.js:58:12)
    at Socket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  parent: Error: getaddrinfo ENOTFOUND db
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3008,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'db'
  },
  original: Error: getaddrinfo ENOTFOUND db
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3008,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'db'
  }
}
Migrations failed, could not run the server app.
✓ 3285 modules transformed.
rendering chunks...
[plugin:vite:reporter]
(!) /code/client/src/components/FeedbackForm.jsx is dynamically imported by /code/client/src/containers/Main.jsx but also statically imported by /code/client/src/components/Navbar.jsx, dynamic import will not move module into another chunk.
computing gzip size...
dist/index.html                                            2.40 kB │ gzip:   0.93 kB
dist/assets/stripe-connection-Mlyc4ibD.webp                4.18 kB
dist/assets/simpleAnalytics-dark-QiCa0yaA.png              4.26 kB
dist/assets/Strapi-dark-85KfiIg7.png                       4.53 kB
dist/assets/ChartMogul-dark-xN_t5yDj.png                   4.59 kB
dist/assets/mongodb-dark-9G0hIr_5.png                      5.72 kB
dist/assets/mongodb-logo-60GIcCcL.png                      6.04 kB
dist/assets/rds-dark-1kjhRXw0.png                          6.56 kB
dist/assets/rds-MpflMIzV.png                               6.66 kB
dist/assets/Stripe-dark-QiirBsCg.png                       7.32 kB
dist/assets/api-dark-8gL5NuQj.png                          7.49 kB
dist/assets/api-i5JsBiyy.png                               7.62 kB
dist/assets/mysql-dark-OLk-zNCD.png                        9.26 kB
dist/assets/logo_blue-891UyiPS.png                        10.65 kB
dist/assets/realtime-db-url-rvp2_b-S.webp                 10.81 kB
dist/assets/mysql-yA-h0RVO.png                            10.84 kB
dist/assets/customerio-d9GdvRQ1.png                       11.66 kB
dist/assets/customerio-dark-nhelsqSp.png                  12.34 kB
dist/assets/GoogleAnalytics-Ds26Bh7I.webp                 13.72 kB
dist/assets/googleanalytics-dark-uMrLG0sI.png             13.74 kB
dist/assets/ChartMogul-S9t9XY1_.webp                      13.94 kB
dist/assets/postgres-dark-5hzok4P2.png                    14.16 kB
dist/assets/firebase-real-time-database-JE73brAe.png      15.28 kB
dist/assets/postgres-rSivrLqB.png                         16.54 kB
dist/assets/Supabase-dark-xkPjDgxu.png                    17.37 kB
dist/assets/plausible-logo-o_4w23lp.png                   18.51 kB
dist/assets/firebase-firestore-xEgCo-ot.png               18.79 kB
dist/assets/mailgun-dark-t1cgerjO.png                     21.38 kB
dist/assets/firebase-dark-IqktMyNg.png                    23.13 kB
dist/assets/mailgun_logo-M2t3skJm.webp                    24.82 kB
dist/assets/firestore-dark-oDrCRZR_.png                   26.70 kB
dist/assets/plausible-dark-2hD7Olq5.png                   28.69 kB
dist/assets/logo_full_dark-SHvz0knG.png                   36.12 kB
dist/assets/logo_full_light-OdnqUld-.png                  40.39 kB
dist/assets/timescaledb-3GEEcsS8.jpg                     117.73 kB
dist/assets/chartbrew-auto-update-kVP02kCp.jpg           121.52 kB
dist/assets/timescaledb-dark-nismRqjc.jpeg               125.07 kB
dist/assets/dashboards_background--t47EXWH.webp          139.67 kB
dist/assets/chartmogul-template-H-SDD4GL.jpeg            238.74 kB
dist/assets/plausible-template-ZQrl0Eo6.jpeg             239.51 kB
dist/assets/mailgun-template-7iqd4uNV.jpeg               275.44 kB
dist/assets/simpleanalytics-template-FJigFIOX.jpeg       294.50 kB
dist/assets/ga-template-w0l7VPBM.jpeg                    316.95 kB
dist/assets/quick-start-video-jnU6AKwJ.jpg               353.79 kB
dist/assets/instruction-dashboard-report-sxwzQEEb.png  1,332.42 kB
dist/assets/ProjectBoard-GTrivq0h.css                      5.46 kB │ gzip:   1.02 kB
dist/assets/index-L8oyBzrg.css                           214.73 kB │ gzip:  27.43 kB
dist/assets/validations-H-C24gFd.js                        0.30 kB │ gzip:   0.25 kB
dist/assets/ProjectRedirect-e3Sbhuu9.js                    0.60 kB │ gzip:   0.37 kB
dist/assets/UserInvite-sdNLXfqq.js                         1.28 kB │ gzip:   0.70 kB
dist/assets/GoogleAuth-6vRPexj1.js                         1.77 kB │ gzip:   0.90 kB
dist/assets/PasswordReset-amvaeYy2.js                      2.31 kB │ gzip:   1.12 kB
dist/assets/ManageTeam-n7T_sppu.js                         2.43 kB │ gzip:   1.06 kB
dist/assets/EmbeddedChart-yfSu2Alt.js                      5.00 kB │ gzip:   1.99 kB
dist/assets/Login-8sx6uALO.js                              6.09 kB │ gzip:   2.19 kB
dist/assets/Signup-tWpUy-Fx.js                             6.70 kB │ gzip:   2.34 kB
dist/assets/ManageUser-Gn1aOs6c.js                         9.35 kB │ gzip:   3.19 kB
dist/assets/PublicDashboard-uCEajjyO.js                   40.20 kB │ gzip:  13.15 kB
dist/assets/ProjectBoard-lFh64XQS.js                     175.26 kB │ gzip:  53.71 kB
dist/assets/index-wdeIiDCN.js                          2,999.46 kB │ gzip: 857.06 kB
✓ built in 13.52s
(!) Some chunks are larger than 500 kB after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
UI built successfully!
```

**Comment by panosru** [comment] 2024-04-25 10:37
I switched to OrbStack (free) and it works out of the box perfectly! No segmentation faults, no extra configs.
