### ISSUE TITLE
Significant performance degradation in docker latest version,  3.5.1

### ISSUE THREAD

**Issue by ttpears** [chartbrew/chartbrew#230] opened 2024-06-10 21:32 UTC
We were attempting to deploy a fresh instance and kept running into server crashes.

node processes running at 100% for most of the time it was running.

Deployed multiple instances, experienced the same behavior until we rolled back to 3.4.0, now happily running using the same config.

One of our devs pointed out the container size had nearly doubled, which hinted us towards rolling back one version.

Once we saw this message, we knew the server had crashed:
````
chartbrew        | ConnectionAcquireTimeoutError [SequelizeConnectionAcquireTimeoutError]: Operation timeout
chartbrew        |     at ConnectionManager.getConnection (/code/server/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:206:15)
chartbrew        |     at runNextTicks (node:internal/process/task_queues:60:5)
chartbrew        |     at process.processTimers (node:internal/timers:511:9)
chartbrew        |     at async /code/server/node_modules/sequelize/lib/sequelize.js:305:26
chartbrew        |     at async MySQLQueryInterface.select (/code/server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:12)
chartbrew        |     at async TeamRole.findAll (/code/server/node_modules/sequelize/lib/model.js:1140:21)
chartbrew        |     at async TeamRole.findOne (/code/server/node_modules/sequelize/lib/model.js:1240:12)
chartbrew        |     at async /code/server/api/ProjectRoute.js:31:20 {
chartbrew        |   parent: TimeoutError: Operation timeout
chartbrew        |       at Timeout.<anonymous> (/code/server/node_modules/sequelize-pool/lib/Deferred.js:17:25)
chartbrew        |       at listOnTimeout (node:internal/timers:573:17)
chartbrew        |       at process.processTimers (node:internal/timers:514:7),
chartbrew        |   original: TimeoutError: Operation timeout
chartbrew        |       at Timeout.<anonymous> (/code/server/node_modules/sequelize-pool/lib/Deferred.js:17:25)
chartbrew        |       at listOnTimeout (node:internal/timers:573:17)
chartbrew        |       at process.processTimers (node:internal/timers:514:7)
````

For what it's worth, we're using ````mysql:latest```` for the container, attempted various MySQL data sources, but seems like the server just slowly dies as node consumes 100% CPU.

```strace``` indicated it was actually running MySQL queries while chewing CPU, but it appeared the queries were Chartbrew related, not our data sources.

Sorry, we don't have much more to go on, other than reverting to 3.4.0 immediately resolved all issues.

**Comment by razvanilin** [comment] 2024-06-11 02:13
Hey @ttpears I'll look into this and try to spot what's going on. The size of the container increased because I changed the Node image when I did the build although I'll have to find a way to make it work with the previous one. I can't think right now why the performance would be affected, but it looks like with the new image, Chartbrew cannot connect to your database and it's getting stuck in a look (hence the 100% cpu usage).

I'll keep this updated with what I find 👌

**Comment by razvanilin** [comment] 2024-06-11 03:58
I think the issue was caused by a `.env` file that sneaked into the build and caused the connection to your database to fail. I just updated the `latest` tag with the fix, as well as the new updates from v3.5.2 that just released now. The image is also smaller like before. The size increase was caused by a dependency that needed python installed

I'll close this for now, but feel free to open the issue again if you're still experiencing problems with `latest`

**Closed by razvanilin** 2024-06-11 03:58 UTC
Labels: bug

**Comment by ttpears** [comment] 2024-06-11 15:36
Wow, thanks for the quick response.  I'll deploy a 2nd copy that they can test side-by-side and we'll report back :+1:

**Comment by ttpears** [comment] 2024-06-12 20:56
So far, the new version looks great, no crashing and everything seems stable, team has been building in it all day.

Again, thanks for the quick response, everyone on the team was surprised to see a turnaround so quickly.

**Comment by razvanilin** [comment] 2024-06-13 03:35
Awesome to hear that 🙌 Usually stuff gets fixed pretty fast around here haha. Feel free to open issues whenever your notice something is not working as intended. I appreciate the help to spot these

By the way, would you be open to complete [this short survey about Chartbrew](https://airtable.com/appVpgeK81xVSaqZo/pagYEbvTqeVubSYby/form)? Just a few questions about your experience with Chartbrew so far. This helps a lot, especially when it comes from active users like your team <3
